var cars = [];
cars.push("BMW");
cars.push("Audi");
cars.push("Civic");
console.log(cars);
console.log("Length = "+cars.length);
console.log("Shift value 1 = "+ cars.shift());
console.log("Shift value 2 = "+ cars.shift());
console.log(cars);
console.log("Length  = "+cars.length);
cars.push("Ferrari");
console.log(cars);
console.log("Length = "+cars.length);
console.log("Shift value 3 = "+ cars.shift());
console.log("Length = "+cars.length);
console.log(cars);  